### ISSUE TITLE
[Bug] If NODE_ENV != production , first time load, search crash component.

### ISSUE THREAD

**Issue by metalice** [patternfly/react-log-viewer#53]
Hello,

if running locally with NODE_ENV != production,

the first time you try to search using the LogViewerSearch component, it crashes with the following msg:

![image](https://github.com/patternfly/react-log-viewer/assets/14824964/54dbe43d-27b7-4691-829d-8156edb441b1)

This is probably caused by <List> component.

**Comment by nicolethoen** [comment]
@metalice 
is there a donut chart in or around your log-viewer?
would you mind including the full stack trace in this issue?

**Comment by metalice** [comment]
> @metalice is there a donut chart in or around your log-viewer? would you mind including the full stack trace in this issue?

stack trace:
TypeError: Cannot read properties of undefined (reading 'getCurrentStack')
    at pushCurrentDebugStack (http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:4876:58)
    at ReactDOMServerRenderer.read (http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:5585:11)
    at Object.renderToString (http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:6199:27)
    at http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:280:95
    at Array.forEach (<anonymous>)
    at http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:277:33
    at Array.forEach (<anonymous>)
    at getFormattedData (http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:270:29)
    at http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:294:356
    at na (http://localhost:9000/static/vendors~main-chunk-cc4bf1e2a3d04b4d5872.min.js:108:58879)

**Comment by metalice** [comment]
component trace if it helps
`at http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:247:69
    at div
    at div
    at List (http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:1410:17)
    at div
    at div
    at http://localhost:9000/api/plugins/kubevirt-plugin/vendors-node_modules_patternfly_react-log-viewer_dist_esm_index_js-chunk.js:44:11
    at VirtualMachineBasicLogViewer (http://localhost:9000/api/plugins/kubevirt-plugin/exposed-VirtualMachineNavPage-chunk.js:10505:41)
    at VirtualMachineLogViewer (http://localhost:9000/api/plugins/kubevirt-plugin/exposed-VirtualMachineNavPage-chunk.js:10567:36)
    at section
    at u (http://localhost:9000/static/vendor-patternfly-4-shared~main-chunk-2148a2be519768c9eeb9.min.js:1:296126)
    at C (http://localhost:9000/static/vendor-patternfly-4-shared~main-chunk-2148a2be519768c9eeb9.min.js:1:622866)
    at div
    at VirtualMachineDiagnosticTab (http://localhost:9000/api/plugins/kubevirt-plugin/exposed-VirtualMachineNavPage-chunk.js:10405:40)
    at component
    at t (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:38632)
    at t (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:40713)
    at HorizontalNavbar (http://localhost:9000/api/plugins/kubevirt-plugin/utils_components_AffinityModal_AffinityModal_tsx-utils_components_CPUMemoryModal_CpuMemoryMod-6512ee-chunk.js:1920:29)
    at div
    at SidebarEditorProvider (http://localhost:9000/api/plugins/kubevirt-plugin/utils_styles_ListPageCreateButton_scss-utils_components_AffinityModal_components_AffinityEdit-da0018-chunk.js:6469:34)
    at VirtualMachineNavPage (http://localhost:9000/api/plugins/kubevirt-plugin/exposed-VirtualMachineNavPage-chunk.js:6683:34)
    at l (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:144430)
    at http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:384473
    at C (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:14964)
    at j (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:385252)
    at k (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:4920)
    at ne (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:10364)
    at Suspense
    at i (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:323611)
    at section
    at m (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:6:146058)
    at div
    at div
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1283445)
    at div
    at div
    at s (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:60:95975)
    at d (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:6:268457)
    at div
    at d (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:6:28504)
    at c (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1054574)
    at http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:294076
    at C (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:14964)
    at main
    at div
    at v (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:60:294494)
    at div
    at div
    at s (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:10:67972)
    at div
    at div
    at s (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:60:95975)
    at d (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:6:268457)
    at div
    at d (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:6:28504)
    at Dn (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:1:125971)
    at t.default (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:732624)
    at t.default (http://localhost:9000/static/quick-start-chunk-b3c23ec6b04573476a59.min.js:1:3361)
    at l (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:144430)
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1363911)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at mt (http://localhost:9000/static/vendor-patternfly-5~main-chunk-68633060ccbd7a59d951.min.js:1:86104)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at ModalProvider (http://localhost:9000/api/plugins/kubevirt-plugin/exposed-modalProvider-chunk.js:44:26)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at ee (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384113)
    at o (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:686520)
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1356158)
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1353738)
    at te (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1384235)
    at ne (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1386254)
    at k (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:4920)
    at ne (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:10364)
    at k (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:4920)
    at ne (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:10364)
    at te (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:31:9773)
    at G (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:11631)
    at t (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:35062)
    at ae (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:1386516)
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:662455)
    at t.a (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:973017)
    at l (http://localhost:9000/static/main-chunk-b32ade8bd768ff34c807.min.js:1:512943)
    at t.a (http://localhost:9000/static/vendor-plugins-shared~main-chunk-27b4acfee6b2f53fcde5.min.js:12:21428)
    at Suspense`

**Comment by metalice** [comment]
> @metalice is there a donut chart in or around your log-viewer? would you mind including the full stack trace in this issue?

Hey , there isn't any donut chart near it, not rendered or hidden
